import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import type {
  DecisionEngineState,
  Recommendation,
  RecommendationStatus,
  RecommendationPriority,
  DeterministicAIContext
} from "@/services/ai-decision-engine";

export function useRealDecisionEngine() {
  const [statusOverrides, setStatusOverrides] = useState<Record<string, RecommendationStatus>>({});

  const setStatus = (id: string, status: RecommendationStatus) => {
    setStatusOverrides((prev) => ({ ...prev, [id]: status }));
  };

  const { data, isFetching, refetch } = useQuery({
    queryKey: ["decision-engine"],
    queryFn: async () => {
      const res = await fetch("/api/ai/decision-engine", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          simulationResult: {},
          scenario: {},
          rootCause: {},
          riskIntelligence: {}
        })
      });
      if (!res.ok) throw new Error("Failed to fetch decision engine data");
      return res.json() as Promise<{ aiExplanation: any; deterministicContext: DeterministicAIContext }>;
    },
    refetchInterval: 30_000
  });

  const engine: DecisionEngineState = (() => {
    if (!data || !data.deterministicContext) {
      return {
        recommendations: [],
        lastAnalysedAt: new Date(),
        cycleCount: 0,
        totalEstimatedSavings: "UNKNOWN",
        modelVersion: "SR-6 Deterministic Bridge",
        analysisStatus: isFetching ? "analysing" : "idle",
        deterministicContext: null
      };
    }

    const recs: Recommendation[] = data.deterministicContext.candidateMitigations.map((mit) => {
      const isCritical = mit.estimatedRecoveryTime === "UNKNOWN" || (mit.estimatedRecoveryTime as number) > 14;
      const priority: RecommendationPriority = isCritical ? "critical" : "high";

      return {
        id: mit.id,
        type: mit.type,
        priority,
        title: "Mitigation: " + mit.type.replace(/_/g, " ").replace(/\b\w/g, c => c.toUpperCase()),
        recommendation: mit.description,
        businessImpact: "Mitigates " + mit.targetRiskId + ".",
        estimatedSavings: data.deterministicContext.portfolioResult?.deduplicatedRevenueDelta ?? "UNKNOWN",
        confidenceScore: 100, // Deterministic logic carries 100% confidence vs heuristic ML
        reasoning: data.aiExplanation?.executiveDecision?.reasonForSelection || "Deterministic action generated by SR-5 mathematical engine.",
        affectedDepartment: "Supply Chain",
        status: statusOverrides[mit.id] ?? "new",
        generatedAt: new Date(),
        sourceEntity: "SR-6 Bridge",
        dataPoints: [
          { label: "Target Risk", value: mit.targetRiskId },
          { label: "Est. Cost", value: mit.estimatedCost === "UNKNOWN" ? "UNKNOWN" : "$" + mit.estimatedCost },
          { label: "Recovery Time", value: mit.estimatedRecoveryTime === "UNKNOWN" ? "UNKNOWN" : mit.estimatedRecoveryTime + " days" },
        ]
      };
    });

    const totalEstimatedSavings = data.deterministicContext.portfolioResult?.deduplicatedRevenueDelta ?? "UNKNOWN";

    return {
      recommendations: recs,
      lastAnalysedAt: new Date(),
      cycleCount: 1,
      totalEstimatedSavings,
      modelVersion: "SR-6 Deterministic Bridge",
      analysisStatus: isFetching ? "analysing" : "complete",
      deterministicContext: data.deterministicContext
    };
  })();

  const refetchAll = () => {
    refetch();
  };

  return { engine, isFetching, refetchAll, setStatus };
}
